### PR TITLE
Add HDMA lake ntopo file settings

### LINKED ISSUE #330: Build problem with latest cesm-coupling branch
I'm getting a build error with the latest cesm-coupling branch on cheyenne_intel, as follows...

The git hash is: f669e9775b04592352c37b996a997e000a653990

```
         - Building rof Library 
Building rof with output to /glade/scratch/erik/SMS_P360x1_Lm1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20221123_225752_dv160r/bld/rof.bldlog.221123-230903
datm built in 1.160864 seconds
/glade/work/erik/ctsm_worktrees/mizuRoute/components/mizuRoute/route/build/cpl/RtmMod.F90(357): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [NR_UTILITY_MODULE]

/glade/work/erik/ctsm_worktrees/mizuRoute/components/mizuRoute/route/build/cpl/RtmMod.F90(357): error #6580: Name in only-list does not exist or is not accessible.   [ARTH]

mizuroute built in 22.193748 seconds
ERROR: BUILD FAIL: mizuroute.buildlib failed, cat /glade/scratch/erik/SMS_P360x1_Lm1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20221123_225752_dv160r/bld/rof.bldlog.221123-230903
```

### PR DESCRIPTION
**Pull request by ekluzek**
Changes to add ability to run the HDMA_lake_mz grid with CESM.

Fixes #330

### CODE REVIEW

**Comment by ekluzek** [comment]
My test case is currently failing in mizuRoute initialization with

SMS_P360x1_Ld1_D.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default

**Comment by nmizukami** [comment]
Hi Erik (@ekluzek),  wondering where in initialization part it failed.  

These are not related to failure, but there are several places in control file that needs to be change (I will have to update control file).  Right now, `is_lake_sim` is not in control file so lake should be turned off, so to activate lake, this tag needs to be included.  Also maybe use cesm-coupling from my repo (once PR #323 is merged, both my repo and ESCOMP are matched).  But lake is turned off now, so I think it runs without fixes in PR #323 (but not 100% sure).

**Comment by nmizukami** [comment]
I also forgot to sort river-lake network data with ID to match up the ID order in ESMF mesh. I put reordered network - /glade/scratch/mizukami/transfer/erik/Network_topology_HDMA_HydroLake_v1_cdf5.nc (it is overwritten).

**Comment by nmizukami** [comment]
Could you add this tag in [SAMPLE-coupled.control](https://github.com/ESCOMP/mizuRoute/blob/cesm-coupling/route/settings/SAMPLE-coupled.control)

`<is_lake_sim>           F                                            ! Switch lake simulation on/off`

**Comment by nmizukami** [comment]
Looks great!  Thank you Erik. I will merge it.

**Pull request merged**
