### PR TITLE
Add some lake tests to the test list update lake dataset and fix some coupled issues

### LINKED ISSUE #238: ERI tests fail because of trouble doing a hybrid startup
ERI tests are failing on the "ref2" step trying to do the hybrid startup piece. The problem is that the restart file is set in mizuroute.control as follows...

`<fname_state_in>       STATE_IN_NC `

And then mizuroute fails trying to read that file:

rof.log
```
  Reading Slope into structure SEG
  Reading seg_id into structure NTOPO
  Reading Tosegment into structure NTOPO
 ERROR: (route_ini)init_state_data/read_state_nc/get_nc_dim_len/[No such file or directory; file=./STATE_IN_NC]
```

I'm guessing likely the same problem will happen on the "branch" step. And I assume this means there is something wrong in the buildnml code for mizuRoute for hybrid or branch run types.

### LINKED ISSUE #262: Connect continue_run in control file in buildnml
continue_run is now a logical variable in the control file. This needs to be connected to the CESM XML variable CONTINUE_RUN in the buildnml. We should also check to make sure the user doesn't try to override the setting from the CESM XML variable.

### LINKED ISSUE #281: Change name of user_ctl_mizuroute file to user_nl_mizuroute_ctl
The cime test handling system only copies over the user_nl_* files over, hence for the user_ctl_ files to work in the test system the name needs to start with user_nl. This is important to get the ER tests working.

### LINKED ISSUE #372: Error in control file for running with CESM
The list of CESM tests is failing with ctsm5.1.dev114 and hash 71d4928273dab4e841a1116da72fc70e9e54691a.

One such test is: SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default

the cesm.log is filled with this:

```
-1: 1832	 1832	   32	yes	 r10i1n33    	   32
-1: 1833	 1833	   33	yes	 r10i1n33    	   33
-1: 1834	 1834	   34	yes	 r10i1n33    	   34
-1: 1835	 1835	   35	yes	 r10i1n33    	   35
459:MPT ERROR: Rank 459(g:459) is aborting with error code 1.
459:	Process ID: 64112, Host: r10i5n2, Program: /glade/scratch/erik/SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k/bld/cesm.exe
459:	MPT Version: HPE MPT 2.25  08/14/21 03:05:20
459:
459:MPT: --------stack traceback-------
512:MPT ERROR: Rank 512(g:512) is aborting with error code 1.
512:	Process ID: 52546, Host: r10i5n9, Program: /glade/scratch/erik/SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k/bld/cesm.exe
512:	MPT Version: HPE MPT 2.25  08/14/21 03:05:20
512:
512:MPT: --------stack traceback-------
114:MPT ERROR: Rank 114(g:114) is aborting with error code 1.
114:	Process ID: 36340, Host: r10i1n18, Program: /glade/scratch/erik/SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k/bld/cesm.exe
114:	MPT Version: HPE MPT 2.25  08/14/21 03:05:20
114:
114:MPT: --------stack traceback-------
299:MPT ERROR: Rank 299(g:299) is aborting with error code 1.
299:	Process ID: 13888, Host: r10i4n3, Program: /glade/scratch/erik/SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k/bld/cesm.exe
299:	MPT Version: HPE MPT 2.25  08/14/21 03:05:20
299:
299:MPT: --------stack traceback-------
542:MPT ERROR: Rank 542(g:542) is aborting with error code 1.
542:	Process ID: 38461, Host: r10i4n32, Program: /glade/scratch/erik/SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k/bld/cesm.exe
```

Last thing in the rof.log file is the read of the control file:

```
---- read control file --- 
 <case_name> --> SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k
 <route_opt> --> 1
 <doesBasinRoute> --> 1
 <is_flux_wm> --> T
 <fname_state_in> --> empty
 <newFileFrequency> --> monthly
 <ancil_dir> --> /glade/p/cesmdata/cseg/inputdata/rof/mizuRoute/ancillary_data/
 <input_dir> --> /glade/scratch/erik/SMS_D_Ld1.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default.20230503_105902_dikw1k/run/
 <output_dir> --> ./
 <fname_ntopOld> --> ntopo_HDMA_lake_mz_Global_cdf5_fill_reorder_c20221130.nc
 <dname_sseg> --> n
 <dname_nhru> --> n
 <fname_ntopNew> --> UPDATED_NTOPO_NC
 <units_qsim> --> mm/s
 <varname_area> --> area
 <varname_length> --> length
 <varname_slope> --> slope
 <varname_HRUid> --> ID
 <varname_hruSegId> --> ID
 <varname_segId> --> ID
 <varname_downSegId> --> ID_next
 <varname_pfafCode> --> PFAF
 <hydGeometryOption> --> 1
 <topoNetworkOption> --> 1
 <computeReachList> --> 1
 <is_lake_sim> --> T
 <varname_D03_MaxStorage> --> S_max
 <varname_D03_Coefficient> --> Coeff
 <varname_D03_Power> --> power
 <varname_islake> --> lake
 <varname_lakeModelType> --> lake_type
 <param_nml> --> mizuRoute_in
 <basRunoff> --> T
 <instRunoff> --> F
 <dlayRunoff> --> F
 <sumUpstreamRunoff> --> F
 <KWTroutedRunoff> --> T
 <IRFroutedRunoff> --> T
 <MCroutedRunoff> --> T
 <KWroutedRunoff> --> T
 <DWroutedRunoff> --> T
 <volume> --> F
```

### LINKED ISSUE #375: ERROR messages don't show up when running coupled...
When running coupled the error messages don't show up in the system. This is part of why #372 wasn't immediately recognized.

The issue is that for most of the ESMF NUOPC cap, setting the rc error code, and returning above is fine when the error is recognized in ESMF. However, this should NOT be done when it's a mizuRoute error. In those cases the code should write the error and abort with a call to shr_sys_abort. In the rest of mizuRoute setting the cmessage and calling return is the correct thing to do.

So calls like this in the NUOPC cap for s function that returns rc are correct:

``` fortran
    call NUOPC_CompDerive(gcomp, model_routine_SS, rc=rc)
    if (ChkErr(rc,__LINE__,u_FILE_u)) return
```

As are things like this:

``` fortran
      if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, line=__LINE__, file=u_FILE_u)) return
```

In the shared and lower levels of mizuRoute error handling is done like this which is fine:

``` fortran
  if(ierr/=0)then; message=trim(message)//trim(cmessage); return; endif
```

At the level of the NUOPC cap however, message should be passed to a call for shr_sys_abort so that the error message from below in mizuRoute is written out to the log file and the CESM is aborted.

### PR DESCRIPTION
**Pull request by ekluzek**
Add some lake tests to the CESM test list. Also add prealpha and prebeta tests, as well as correcting some issues in the test list including the grid names.

Fixes #372
Fixes #375
Fixes #262
Fixes #238 
Fixes #281

### CODE REVIEW

**Comment by ekluzek** [comment]
Right now all of the tests are failing.

**Review by nmizukami — COMMENTED** [review]
Hi Erik,   changes in SAMPLE-coupled.control is duplicated with #374.  I will close #374 since this is including dt_qsim fix, and keep this.

**Comment by ekluzek** [comment]
Running the test list shows the issues #376 and #377. The 5x5_amazon_rHDMA tests also need a testmod since ccs_config isn't setup correctly for that grid.

**Comment by ekluzek** [comment]
List that pass:

PFS.f19_f19_rHDMA_mg17.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default			
PFS.f19_f19_rHDMA_mg17.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default			
SMS_D.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default			
SMS_D.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default			
SMS_D.nldas2_nldas2_rUSGS_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default			
SMS_P720x4.nldas2_nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default			
SMS_P720x4.nldas2_nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default

**Comment by ekluzek** [comment]
With fixes coming in more things are passing now. There are 11 restart tests that should pass when #381 comes in. And 11 tests are passing now.

I have this list of 15 tests that are failing though in the run phase...

```
ERI.nldas2_nldas2_rHDMA_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default	  RUN		
ERP_D_P1x25.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default	  RUN		
ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-5x5_amazon_rHDMA	  RUN		
ERS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-5x5_amazon_rHDMA	  RUN		
ERS.f19_f19_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default	  RUN		
ERS_D.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-5x5_amazon_rHDMA	  RUN		
ERS_D.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-5x5_amazon_rHDMA	  RUN		
PET_P1x36.nldas2_nldas2_rMERIT_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default	  RUN		
SMS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-5x5_amazon_rHDMA	  RUN		
SMS.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-5x5_amazon_rHDMA	  RUN		
SMS.f09_f09_rHDMAlk_mg17.I2000Clm50SpMizGs.cheyenne_gnu.mizuroute-default	  RUN		
SMS.hcru_hcru_mt13.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-hcru	  RUN		
SMS.hcru_hcru_rHDMAlk_mt13.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-hcru	  RUN		
SMS_D.nldas2_nldas2_rUSGS_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-MERIT	  RUN		
SMS_Ly2.5x5_amazon_rHDMA.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-5x5_amazon_rHDMA_Monthly	  RUN	
```

It's not clear what's going wrong with the above list.

**Comment by ekluzek** [comment]
hcru_hcru_mt13 is the half-degree atmosphere and land with a t13 ocean mask where t13 is a high resolution ocean grid. I think it's roughly tenth degree, the gx1v7 ocean grid is roughly 1-degree, so for half degree you need a higher resolution ocean mask.

And yes this uses the new ntopo file for HDMA_lake. I'll try f09_f09_rHDMAlk_mg17 for intel to see if that works for me, so I can contrast it with the gnu case.

**Comment by ekluzek** [comment]
Note, for this case: SMS_D.nldas2_nldas2_rUSGS_mnldas2.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-MERIT I have a 720x4 PE layout case that works, and the 1800x1 PE layout fails as below in the mesh create. I'm wondering if coupled mizuRoute will only work for certain sizes of PE layouts for some grids.


```
20230516 143529.864 ERROR            PET1820 ESMCI_MeshCap.C:2237 MeshCap::meshcreateredistelems() Internal error: Bad condition  - Internal subroutine call returned Error
20230516 143529.864 ERROR            PET1820 ESMF_Mesh.F90:3534 ESMF_MeshCreateRedist() Internal error: Bad condition  - Internal subroutine call returned Error
20230516 143529.864 ERROR            PET1820 rof_comp_nuopc.F90:594 Internal error: Bad condition  - Passing error in return code
20230516 143529.864 ERROR            PET1820 ESM0001:src/addon/NUOPC/src/NUOPC_Driver.F90:2725 Internal error: Bad condition  - Phase 'IPDv01p3' Initialize for modelComp 4: ROF did not return ESMF_SUCCESS
20230516 143529.864 ERROR            PET1820 ESM0001:src/addon/NUOPC/src/NUOPC_Driver.F90:1891 Internal error: Bad condition  - Passing error in return code
20230516 143529.864 ERROR            PET1820 ensemble:src/addon/NUOPC/src/NUOPC_Driver.F90:2725 Internal error: Bad condition  - Phase 'IPDv02p3' Initialize for modelComp 1: ESM0001 did not return ESMF_SUCCESS
20230516 143529.864 ERROR            PET1820 ensemble:src/addon/NUOPC/src/NUOPC_Driver.F90:1895 Internal error: Bad condition  - Passing error in return code
20230516 143529.864 ERROR            PET1820 ensemble:src/addon/NUOPC/src/NUOPC_Driver.F90:481 Internal error: Bad condition  - Passing error in return code
20230516 143529.864 ERROR            PET1820 esmApp.F90:134 Internal error: Bad condition  - Passing error in return code
20230516 143529.864 INFO             PET1820 Finalizing ESMF
```

**Comment by nmizukami** [comment]
I think for lake, need to initialize precipitation and evaporation arrays with zero explicitly.  right now those arrays are allocated but not initialized with a particular value (https://github.com/ESCOMP/mizuRoute/blob/37b2fb5ecce7af5abfb64d8f5b862c78a512841c/route/build/src/mpi_process.f90#L570) and precipitation and evaporation are not passed from the coupler, but use them to compute water balance.  gnu and intel put different array values after allocated. I think intel put zero, but gnu put some random number (or large number).  So that may be intel works but gnu does not (gnu run produce water balance error, so terminated)

**Comment by ekluzek** [comment]
Ahhh, nice analysis. Yes, that is something we should make sure we do explicitly initialize to zero.

**Comment by nmizukami** [comment]
yes, I just tested this hypothesis and now gnu runs ok.

**Comment by ekluzek** [comment]
@nmizukami awesome  can you add those changes to your restart PR so we have them coming in?

**Comment by ekluzek** [comment]
OK, this is ready to be merged in from my perspective.

**Comment by nmizukami** [comment]
As far as I can see the changes in F90 files, looks good to me.  I think it is ready to be merged too.

**Comment by ekluzek** [comment]
@nmizukami I went ahead and merged it since you said it looked OK. I had done my testing with it.

**Pull request merged**
