### PR TITLE
remove manage_externals

### PR DESCRIPTION
**Pull request by jedwards4b**
Remove manage externals from the mizuRoute repository

Part of #450

### CODE REVIEW

**Comment by ekluzek** [comment]
@jedwards4b thanks so much for putting this PR together. We appreciate your doing it.

Note, that we weren't planning on making this a requirement for cesm3_0_beta01, as the only need for externals management for mizuRoute is for the standalone version. So we figure this can come in after cesm3_0_beta01 is done.

**Comment by nmizukami** [comment]
Thanks Jim (@jedwards4b) for starting this, One thing I would like to check before merging this is:
do we have to have alternative to pull externals? Here PIO. I cannot remember what the new method is to replace manage external. git submodule??

**Comment by jedwards4b** [comment]
@nmizukami git-fleximod is the replacement.  I can add it to this PR but won't do it now as apparently this update is to be deferred.

**Comment by ekluzek** [comment]
We also need to bring in git-fleximod as a subtree as documented here:

https://github.com/ESMCI/git-fleximod/wiki#including-git-fleximod-in-other-repositories

**Comment by ekluzek** [comment]
@nmizukami will bring this in as is as the second step to moving to git-fleximod. We will do another PR to bring git-fleximod in as a git subtree.

**Review by ekluzek — APPROVED** [review]
This can happen now that git-fleximod was merged into mizuRoute.

**Pull request merged**
